### ISSUE TITLE
Add percentage

### ISSUE THREAD

**Issue by saman** [mamal72/dgkala-web#1]
Thanks for your helpful project. Would you add the percentage of discounts?

**Comment by mamal72** [comment]
Thanks for the suggestion. Yup. I'll add it. 👍 😁

**Comment by mamal72** [comment]
@saman It's fixed, pushed on master and deployed on Github Pages.
Please test it in Private/Incognito Browsing and do a hard reload and close the issue if you think it's OK. 😁
