### ISSUE TITLE
DigiKala API has changed

### ISSUE THREAD

**Issue by saman** [mamal72/dgkala-web#3]
It seems the DigiKala previous API does not work anymore. I think you should use [the new one](https://search.digikala.com/api2/Data/Get?incredibleOnly=true).

**Comment by mamal72** [comment]
Thanks for the issue. I'll refactor it now. 🙏
But at the current moment, this new API does not return images. Their Android app is not working for me too! So, I'll remove images for now and will replace them with real images as soon as I get an API for this.
